advertising = read.csv("data/Advertising.csv", header = T)
pdf("images/histogram-sales.pdf")
hist(advertising$Sales, xlab="Sales", main="Histogram of Sales")
dev.off()
png("images/histogram-sales.png")
hist(advertising$Sales, xlab="Sales", main="Histogram of Sales")
dev.off()
pdf("images/histogram-tv.pdf")
hist(advertising$TV, xlab="TV", main="Histogram of TV")
dev.off()
png("images/histogram-tv.png")
hist(advertising$TV, xlab="TV", main="Histogram of TV")
dev.off()
sink("data/eda-output.txt")
cat("Advertising TV Summary Statistics\n")
summary(advertising$TV)
cat("Advertising Sales Summary Statistics\n")
summary(advertising$Sales)
sink()
