advertising = read.csv("data/Advertising.csv", header = T)
model = lm(Sales ~ TV, data=advertising)
pdf("images/scatterplot-tv-sales.pdf")
plot(Sales~TV, data=advertising)
abline(model,col='red')
dev.off()
png("images/scatterplot-tv-sales.png")
plot(Sales~TV, data=advertising, main="Plot of TV and Sales")
abline(model,col='red')
dev.off()
save(model, file="data/regression.RData")
